# Generated by Django 4.0.2 on 2022-02-04 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0002_prefecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='eat',
            name='pref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='testRoot.prefecode'),
        ),
        migrations.AddField(
            model_name='play',
            name='pref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='testRoot.prefecode'),
        ),
    ]
