# Generated by Django 4.0.2 on 2022-02-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0003_eat_pref_play_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='eat',
            name='ido',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='eat',
            name='keido',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='ido',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='keido',
            field=models.FloatField(null=True),
        ),
    ]
