# Generated by Django 4.0.2 on 2022-02-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0004_eat_ido_eat_keido_play_ido_play_keido'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('eat', 'ご飯'), ('play', '遊び')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ido', models.FloatField(null=True)),
                ('keido', models.FloatField(null=True)),
                ('pref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='testRoot.prefecode')),
            ],
        ),
    ]
