# Generated by Django 4.0.2 on 2022-02-10 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0006_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofplace',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='testRoot.city'),
        ),
    ]
