# Generated by Django 4.0.2 on 2022-02-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0008_city_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
