# Generated by Django 4.0.2 on 2022-02-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0009_remove_city_image_play_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofplace',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
