# Generated by Django 4.0.2 on 2022-02-15 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testRoot', '0012_typeofplace_atmosphere'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootName', models.CharField(max_length=255)),
                ('name1', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('ido1', models.FloatField(null=True)),
                ('keido1', models.FloatField(null=True)),
                ('name2', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('ido2', models.FloatField(null=True)),
                ('keido2', models.FloatField(null=True)),
                ('name3', models.CharField(max_length=255)),
                ('address3', models.CharField(max_length=255)),
                ('ido3', models.FloatField(null=True)),
                ('keido3', models.FloatField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
