# Generated by Django 4.0.2 on 2022-02-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0016_remove_typeofplace_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofplace',
            name='city',
        ),
    ]
