# Generated by Django 4.0.2 on 2022-02-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0017_remove_typeofplace_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveroot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
