# Generated by Django 4.0.2 on 2022-02-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0023_keeproot'),
    ]

    operations = [
        migrations.AddField(
            model_name='keeproot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
