# Generated by Django 4.0.2 on 2022-02-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0024_keeproot_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofplace',
            name='good',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
