# Generated by Django 4.0.2 on 2022-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0026_typeofplace_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofplace',
            name='image',
            field=models.ImageField(null=True, upload_to='medi/images/'),
        ),
    ]
