# Generated by Django 4.0.2 on 2022-02-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0029_alter_typeofplace_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofplace',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
