# Generated by Django 4.0.2 on 2022-02-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0031_typeofplace_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofplace',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
