# Generated by Django 4.0.2 on 2022-02-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testRoot', '0032_alter_typeofplace_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testRoot.typeofplace')),
            ],
        ),
    ]
