# Generated by Django 4.0.2 on 2022-02-23 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testRoot', '0034_alter_comments_comment_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testRoot.typeofplace'),
        ),
    ]
